### ISSUE TITLE
Vertical menu scroll needs improvement (last item in list isn't visible)

### ISSUE THREAD

**Issue by SofiaMalmsten** [ArchitudeSweden/FileMaker_Timelines#43]
Last items are not visible when all the groups are expanded....
<img width="1008" alt="issue43" src="https://user-images.githubusercontent.com/38439590/43326399-1069f79a-91b9-11e8-8c39-412634ffc4e5.png">

**Comment by richmalm** [comment]
Om det är något att visa så hör av dig.😘

Qvadis AB
Richard.malmsten@qvadis.se
070-4221100

Med vänlig hälsning,
Richard
